version: '3'
services:
  frontend:
    build: .
    ports:
      - '8080:80'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost || exit 1']
      interval: 1m30s
      timeout: 10s
      retries: 3
